### ISSUE TITLE
Trainning Result Nothing?

### ISSUE THREAD

**Issue by fenngMing** [SigmaBM/robosumo-selfplay#1]
I tried to training the robotsumo-Ant-Vs-Ant-v0  problem using your code,  but found no meaning results;  I also found a strange situation that the total reward/dense reward didn't increse even in the begining stage of training; have you succed reproduce the paper's result?

**Comment by SigmaBM** [comment]
The `epdenserewmean` shown in log table is the average of the total dense reward in each episode, so maybe it will be clear to see the average dense reward of each step. As for the total reward, since model 1 is randomly selected from the historical version of model 0, the total reward is affected by the strength of model 1. Therefore, there is no guarantee that the dense reward and total reward will keep increasing. I uploaded `play.py` and you can use it to see if the latest model could beat the earlier model.

I tried this code, it did learn something but can't reach the level of models provided by RoboSumo environment, maybe because of some unmentioned tricks in the original paper or the insufficient sample size (I used `num_env=10`).
